# Generated by Django 2.2.3 on 2021-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de la sucursal'),
        ),
    ]
