# Generated by Django 2.2.3 on 2021-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0004_auto_20211019_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
            ],
        ),
    ]
