# Generated by Django 2.2.3 on 2021-10-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0006_prueba_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='nombre',
            new_name='nombrde',
        ),
    ]
