# Generated by Django 2.2.3 on 2021-10-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0007_auto_20211020_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='nombrde',
            new_name='nombre',
        ),
    ]
