# Generated by Django 2.2.3 on 2021-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0008_auto_20211020_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='apellido',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
