# Generated by Django 2.2.3 on 2021-10-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0011_prueba_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Usuarios', verbose_name='Administrador'),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
