# Generated by Django 2.2.3 on 2021-11-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20211118_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
