# Generated by Django 2.2.3 on 2021-11-18 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0003_delete_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('img', models.CharField(max_length=50, verbose_name='Img')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de registro')),
                ('fecha_baja', models.DateField(null=True, verbose_name='Fecha de baja')),
                ('fecha_modificacion', models.DateField(null=True, verbose_name='Fecha del ultimo cambio')),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
        ),
    ]
