# Generated by Django 2.2.3 on 2021-11-18 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterField(
            model_name='areas',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='areas',
            table='docente',
        ),
    ]
