# Generated by Django 2.2.3 on 2021-11-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_auto_20211118_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='areas',
            table='areas',
        ),
    ]
