# Generated by Django 2.2.3 on 2021-11-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_auto_20211118_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Usuarios', verbose_name='Administrador'),
        ),
    ]
