# Generated by Django 2.2.3 on 2021-11-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_auto_20211118_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='img',
            field=models.ImageField(null=True, upload_to='articulos'),
        ),
    ]
