# Generated by Django 2.2.3 on 2021-11-19 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_auto_20211118_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={},
        ),
        migrations.AlterModelTable(
            name='areas',
            table=None,
        ),
    ]
