# Generated by Django 2.2.3 on 2021-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_auto_20211118_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='img',
            field=models.ImageField(null=True, upload_to='articulos/%Y/%m/%d/', verbose_name='Img'),
        ),
    ]
