# Generated by Django 2.2.3 on 2021-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_auto_20211118_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='img',
            field=models.ImageField(null=True, upload_to='areas/%Y/%m/%d/', verbose_name='Img'),
        ),
    ]
