# Generated by Django 2.2.3 on 2021-11-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211026_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(choices=[('superusuario', 'Super Usuario'), ('administrador', 'Administrador')], max_length=20, verbose_name='Cargo'),
        ),
    ]
