# Generated by Django 2.2.3 on 2021-11-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='img',
            field=models.CharField(default='img/usr-all.jpg', max_length=30, null=True, verbose_name='Imagen'),
        ),
    ]
