# Generated by Django 2.2.3 on 2021-10-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superSu', '0002_auto_20211019_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Licencias'),
            preserve_default=False,
        ),
    ]
