# Generated by Django 2.2.3 on 2021-10-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0005_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='nombre',
            field=models.CharField(default=2, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
