# Generated by Django 2.2.3 on 2021-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superSu', '0010_auto_20211020_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='apellido',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido'),
        ),
    ]
